language: python
python:
- "2.7"
- "3.5"
- "3.6.7"
- "3.6.8"
- "3.7.1"
- "3.7.2"

# normally need something like tox-travis to avoid running every env N times.
# but our tox,ini only defines 1 env (python) because we already expect to
# manage python versions outside of tox. ie: travis is doing the same thing as
# our local test_all_envs.sh.
install: pip install tox
script: tox

deploy:
  matrix:
  - provider: pypi
    user: __token__
    password:
      secure: 0QK2TZNBxwdiEDI7qXfYQHJIVYuFwLTCX8Q7LxSmnRxYXOp8M1KS+E9O3s3QVmeDfg+tNkr6ZhlZcyTZZ4Kegstmm7cG0bQcGl9Riml8IMLHL/UTzs3xz2phgqANbwownuM4D71DfHhzhCYQKPr5rEQdLW+Da6NuwUY0RwS2l0Dj15RJpMcDRp+K3OSL1RHLd029cI5f+UGPRhhMnkq3NMZS7nOUt356E3m4epSK28g+uFqLTDA2abKttIIBaN7C+fM0yjaS99/fhDNx+FspEuqeUA5oJGae6wGw/VOSQH+lVmfqIbEWyRaQoO1GbSZ7nU+oX0FhlDTKrK+yWFQATBE+xBlyp3Fnmqs7rXt5FqE3hv3Pe9Qz8S5rihII7B6k1Y1RS3fBJm3TbyDHXoECt7HSNTG6U2w7Grjla5gcv2L7prn5XAyvU4v7qxWL3E+fmLAbQDnr3eySyfeOw9soV58uo90DdhKcZ+aYs6RY3++6xtUiDmpPHIRGWhJiH38eAwAKzYTglgqN+5fSHzD4RkXj7Wz4nrlQE+W7gzFqIUzTe0hTSXAM7syUkVpx6Amq+rsmOq3zWDzuEJWuZlRUwZLnDMC6tLl0vwDgQPTPoqughSlJ6kBVIWvDDtzbbhmQbQ3vhl6+zdRSJO2ah6kpd1mGtY+8e3qq2BmFKUWikKg=
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_existing: true
    on:
      branch: master
      tags: true
